### ISSUE TITLE
This package doesn't do the one thing it claims it does

### ISSUE THREAD

**Issue by kaiyoma** [joeferner/node-openport#10]
This package does not find open ports. You can test this easily with this simple script:

```
const openport = require('openport');

openport.find({ startingPort: 4001, endingPort: 4999 }, (err, port) => {
  if (err) {
    console.error(err);
  } else {
    console.log(`Success! Port ${port} is open.`);
  }
});
```

If I already have a process listening to port 4001, this script still reports 4001 as open!

```
$ netstat -an | grep LISTENING | grep 4001
  TCP    0.0.0.0:4001           0.0.0.0:0              LISTENING

$ node openport-test.js
Success! Port 4001 is open.
```

Switching to the `ports` argument doesn't work either.

OS: Windows 10
Node: 10.13.0
openport: 0.0.5

**Comment by joeferner** [comment]
Strange, using your test program, I got this...

```
$ ss -ln | grep LISTEN | grep 400
tcp               LISTEN              0                    128    *:4001                                                    *:*                     
tcp               LISTEN              0                    128    *:4002                                                    *:*

$ node test
Success! Port 4003 is open.
```

Are you using Windows WSL (Windows Subsystem for Linux)? I'm wondering if it has something to do with this (https://www.nextofwindows.com/allow-server-running-inside-wsl-to-be-accessible-outside-windows-10-host).

This module runs a simple test on each port. For each port I try to open a server on that port. If it opens successful I assume that port is open. My guess is that WSL allows the port to open within the WSL environment even though the port might be open outside of WSL since it looks like the networks stacks are a little different.

Unfortunately I don't have a Windows environment to test this out on.

**Comment by kaiyoma** [comment]
I don't think I'm using WSL, but I am using the Unix-like subsystem that comes with git bash. FWIW, portfinder (https://github.com/indexzero/node-portfinder) has an almost identical user-facing API and works correctly on Windows.

**Comment by joeferner** [comment]
marked this package as deprecated in favor of portfinder
